# Generated by Django 3.2.6 on 2021-09-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_myshop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='myshop',
            name='bkash_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myshop',
            name='contact_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
