# Generated by Django 3.2.6 on 2021-09-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210913_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/'),
        ),
    ]
