# Generated by Django 3.2.6 on 2021-09-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='phone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
