# Generated by Django 3.2.6 on 2021-08-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='top_sell',
            field=models.BooleanField(default=False),
        ),
    ]
