# Generated by Django 3.2.6 on 2021-08-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='consume',
            field=models.BooleanField(default=False),
        ),
    ]
