# Generated by Django 3.2.6 on 2021-08-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_cart_consume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone_no', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('address', models.TextField()),
                ('address_two', models.TextField()),
                ('payment', models.CharField(max_length=120)),
                ('bkash_no', models.CharField(blank=True, max_length=120, null=True)),
                ('bkash_trans', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
