# Generated by Django 3.2.6 on 2021-08-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0013_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='past_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
