# Generated by Django 3.2.6 on 2021-08-31 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('home_page', '0014_products_past_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='accounts.profileuser'),
        ),
    ]
