# Generated by Django 3.2.6 on 2021-09-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0016_products_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shop_owner',
            field=models.BooleanField(default=False),
        ),
    ]
