# Generated by Django 3.2.6 on 2021-09-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0017_products_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
